In [44]:
import numpy as np

In [46]:
A = np.array([[2, 4], [5, -6]]) #2X2
B = np.array([[9, -3], [3, 6]]) #2X2

In [48]:
A+B #Kan kun legge sammen matiser med samme dimensjon. 

array([[11,  1],
       [ 8,  0]])

In [50]:
A = np.array([[3, 6, 7], [5, -3, 0]]) #2X3
B = np.array([[1, 1], [2, 1], [3, -3]]) #3X2

In [52]:
A.dot(B) #Kan kun mulipliserer matiser, der den ene matiserens rad er den andres koloner; r X k og k X r

array([[ 36, -12],
       [ -1,   2]])

In [60]:
A.transpose() #A^T Her er elementene i radene og kolonene omvendt i fra orginalen

array([[ 3,  5],
       [ 6, -3],
       [ 7,  0]])

In [62]:
B.transpose() #B^T

array([[ 1,  2,  3],
       [ 1,  1, -3]])