In [11]:
import numpy as np

In [13]:
#a)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [15]:
B = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

In [19]:
AB = A*B
print(AB)

[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [ ]:
BA = B*A
print(AB)